config/routes.rb
Rails.application.routes.draw do
  resources :reminders

  root 'reminders#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/account.rb
class Account

  def reminders
    Reminder
  end

end

app/models/recipient.rb
class Recipient

  def email
    "hopper.derek@gmail.com"
  end

end

app/models/reminder.rb
# == Schema Information
#
# Table name: reminders
#
#  id           :integer          not null, primary key
#  account_id   :integer
#  user_id      :integer
#  content      :text             default("")
#  html_content :text             default("")
#  postcard     :boolean          default(FALSE)
#  phone        :boolean          default(FALSE)
#  sms          :boolean          default(FALSE)
#  email        :boolean          default(FALSE)
#  scheduled_at :datetime
#  sent_at      :datetime
#  deleted_at   :datetime
#  created_at   :datetime
#  updated_at   :datetime
#

class Reminder < ActiveRecord::Base
  belongs_to :account
  belongs_to :user

  validate :at_least_one_send_option
  validates :scheduled_at, presence: { allow_blank: false, message: "There was a problem parsing your date and time. Try something like 10/12/2014 and 7:15AM." }
  validates :content, presence: { allow_blank: false, message: "Please tell us about your reminder." }

  attr_accessor :scheduled_at_date, :scheduled_at_time

  def self.scheduled
    where(deleted_at: nil).order("scheduled_at ASC")
  end

  def archive!
    update_attributes(deleted_at: Time.now)
  end

  def editable?
    Time.now < scheduled_at
  end

private

  def at_least_one_send_option
    unless postcard || phone || sms || email
      errors.add(:method, "Please select at least one of postcard, phone call, text message, or email.")
    end
  end

end

app/models/user.rb
class User

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_account, :current_user

private

  def current_account
    Account.new
  end

  def current_user
    User.new
  end

  def render_js_error(model)
    render template: "shared/js/error", locals: { model: model }
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController

  respond_to :json, except: :edit
  respond_to :js, except: :index
  respond_to :html, only: [:index, :edit]

  def index
    @reminders = current_account.reminders.scheduled.decorate
    respond_with(@reminders)
  end

  def create
    @reminder = Reminder.new(reminder_params)
    respond_with(@reminder) do |format|
      if @reminder.save
        flash.now[:notice] = "Good news! We just scheduled your reminder."

        format.js
      else
        flash.now[:error] = "Oops! Something went wrong. Check out the errors below."

        format.js { render_js_error(@reminder) }
      end
    end
  end

  def edit
    @reminder = current_account.reminders.find(params[:id]).decorate
    flash.now[:notice] = "This reminder was originally scheduled for #{@reminder.scheduled_at_time} on #{@reminder.scheduled_at_date}."
    respond_with(@reminder)
  end

  def update
    @reminder = current_account.reminders.find(params[:id])
    respond_with(@reminder) do |format|
      if @reminder.update_attributes(reminder_params)
        flash[:notice] = "Great! Your reminder has been updated."

        format.js
      else
        flash.now[:error] = "Oops! Something went wrong. Check out the errors below."

        format.js { render_js_error(@reminder) }
      end
    end
  end

  def destroy
    @reminder = current_account.reminders.find(params[:id])
    @reminder.archive!
    respond_with(@reminder)
  end

private

  def reminder_params
    params
      .require(:reminder)
      .permit(
        :content,
        :postcard,
        :phone,
        :sms,
        :email,
        :scheduled_at_date,
        :scheduled_at_month,
      )
      .merge(scheduled_at: parsed_scheduled_at)
      # .merge(user: current_user)
      # .merge(account: current_account)
  end

  def parsed_scheduled_at
    Timeliness.parse("#{scheduled_at_date} #{scheduled_at_time}")
  end

  def scheduled_at_date
    @scheduled_at_date ||= strip_whitespace(params[:reminder].delete(:scheduled_at_date))
  end

  def scheduled_at_time
    @scheduled_at_time ||= strip_whitespace(params[:reminder].delete(:scheduled_at_time))
  end

  def strip_whitespace(string)
    string.gsub(" ", "") rescue nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Jimbot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

  <div class="container app">
    <div class="row">
      <div class="col-sm-12">
        <div class="header">
          <span class="h1">Jimbot</span>
          <span class="h5">Send reminder postcards, phone calls, text messages, and emails.</span>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to "Reminders", reminders_path %></li>
          <li><%= link_to "API", '#' %></li>
          <li><%= link_to "My Account", '#' %></li>
        </ul>
      </div>

      <div class="col-sm-9">
        <% if flash[:notice] %>
          <div class="alert alert-info">
            <%= flash[:notice] %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/reminders/_deleted.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Your reminder was deleted</h3>
  </div>
  <div class="panel-body">
    <%= link_to "Back to reminders →", reminders_path %>
  </div>
</div>

app/views/reminders/_form.html.erb
<%= form_for reminder, remote: true, html: { id: "reminder-form" } do |f| %>
  <div class="form-group">
    <%= f.label :content, "What do you want to say?", class: "control-label" %>
    <%= f.text_area :content, class: "form-control", rows: 3 %>
  </div>

  <label class="control-label" for="reminder_method">
    How do you want to send it?
  </label>

  <div class="form-group">
    <label class="checkbox-inline">
      <%= f.check_box :postcard %> Postcard
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :phone %> Phone Call
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :sms %> Text Message
    </label>
    <label class="checkbox-inline">
      <%= f.check_box :email %> Email
    </label>
  </div>

  <div class="form-group">
    <%= f.label :scheduled_at, "When should we send it?", class: "control-label" %>
    <div class="row">
      <div class="col-sm-4">
        <%= f.label :scheduled_at_date, "Date" %>
        <%= f.text_field :scheduled_at_date, class: "form-control", data: { provide: "datepicker", date_autoclose: true  } %>
      </div>
      <div class="col-sm-4">
        <%= f.label :scheduled_at_time, "Time" %>
        <%= f.text_field :scheduled_at_time, class: "form-control" %>
      </div>
    </div>
  </div>

  <%= f.submit reminder.submit_text, class: "btn btn-primary", data: { disable_with: "Scheduling..." } %>

  <% if reminder.persisted? %>
    <%= link_to "Delete", reminder_path(reminder), class: "btn btn-default btn-hover-danger pull-right", method: :delete, data: { remote: true, confirm: "Are you sure you want to delete this reminder?" } %>
  <% end %>
<% end %>

app/views/reminders/_reminder.html.erb
<tr id="reminder-<%= reminder.id %>">
  <td>
    <% if reminder.editable? %>
      <%= link_to "Edit", edit_reminder_path(reminder), class: "edit-reminder" %>
    <% end %>
  </td>
  <td>
    <%= reminder.scheduled_at_date %><br>
    <%= reminder.scheduled_at_time %>
  </td>
  <td><%= simple_format reminder.content %></td>
  <td></td>
  <td class="reminder-methods">
    <span class="glyphicon <%= reminder.postcard_classes %>"></span>
    <span class="glyphicon <%= reminder.phone_classes %>"></span>
    <span class="glyphicon <%= reminder.sms_classes %>"></span>
    <span class="glyphicon <%= reminder.email_classes %>"></span>
  </td>
</tr>

app/views/reminders/edit.html.erb
<%= render 'reminders/form', reminder: @reminder %>

app/views/reminders/index.html.erb
<%= render 'reminders/form', reminder: Reminder.new.decorate %>

<hr>

<table class="table table-schedule">
  <thead>
    <tr>
      <th></th>
      <th>Date</th>
      <th>Content</th>
      <th>Recipient</th>
      <th>Medium</th>
    </tr>
  </thead>
  <%= render @reminders %>
</table>

app/views/shared/_error.html.erb
<div class="form-error text-danger"><%= error %></div>